nekland_admin:
    resources:
        event:
            name: event
            classes:
                model: App\Entity\Project
            properties:
                id:
                    label: "#"
                    editable: false
                name:
                    label: "Name"
                command:
                    label: "Command"
