nekland_admin:
    resources:
        project:
            name: project
            classes:
                model: App\Entity\Project
            properties:
                id:
                    label: "#"
                    editable: false
                name:
                    label: "Name"
                command:
                    label: "Command"
                repo:
                    label: "Repository"
                script:
                    label: "Script to execute before the deployment"
