homepage:
    path: /
    defaults:
        _controller: 'App:Home:home'


deploy:
    path: /deployements/{id}
    defaults:
        _controller: 'App:Deploy:deployFromWeb'

api_deploy:
    path: /api/deployments/{id}
    defaults:
        _controller: 'App:Deploy:deployFromApi'
